name: brew livecheck
on:
  schedule:
    - cron:  '*/20 * * * *'
  workflow_dispatch:

jobs:
  livecheck:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Set up tap ian4hu/clipy
        run: brew -v && brew install grep && brew tap -d ian4hu/clipy

      - name: Run brew livecheck
        run: brew livecheck --tap ian4hu/clipy

      - name: Collect updates & commit
        run: bash .github/workflows/livecheck.sh
        env:
          GITHUB_API_TOKEN: ${{ github.token }}