name: brew livecheck
on:
  schedule:
    - cron:  '*/20 * * * *'
  workflow_dispatch:

jobs:
  livecheck:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        # uses: Homebrew/actions/setup-homebrew@master
        run: which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up tap ian4hu/clipy
        run: brew -v && brew install grep jq && brew tap ian4hu/clipy

      - name: Run brew livecheck
        run: brew livecheck --tap ian4hu/clipy

      - name: Collect updates & commit
        run: bash .github/workflows/livecheck.sh
        env:
          GITHUB_API_TOKEN: ${{ github.token }}