name: brew livecheck
on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
    
jobs:
  livecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up tap ian4hu/clipy
        run: brew tap ian4hu/clipy

      - name: Run brew livecheck
        run: brew livecheck --tap ian4hu/clipy

      - name: Collect updates & commit
        run: bash .github/workflows/livecheck.sh
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}