name: brew livecheck
on:
  schedule:
    - cron:  '*/20 * * * *'
  workflow_dispatch:

jobs:
  livecheck:
    runs-on: macos-latest
    steps:
      - name: Get Brew install script
        id: brew-script
        run: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o brew-install.sh

      - name: Cache Homebrew Bundler RubyGems
        id: cache-brew
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/brew
            /usr/local/share/doc/homebrew
            /usr/local/share/man/man1/brew.1
            /usr/local/share/zsh/site-functions/_brew
            /usr/local/etc/bash_completion.d/brew
            /usr/local/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('brew-install.sh') }}
      - name: Set up Homebrew
        # uses: Homebrew/actions/setup-homebrew@master
        run: which brew || /bin/bash -c "$(cat brew-install.sh)"

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up tap ian4hu/clipy
        run: brew -v && brew install grep jq && brew tap ian4hu/clipy

      - name: Run brew livecheck
        run: brew livecheck --tap ian4hu/clipy

      - name: Collect updates & commit
        run: bash .github/workflows/livecheck.sh
        env:
          GITHUB_API_TOKEN: ${{ github.token }}